In [47]:
import numpy as np

In [48]:
a = np.array([5, 6])
b = np.array([3, 4])

print(a + b)

[ 8 10]


In [49]:
a = np.array([5, 6])
b = np.array([3, 4])

print(a - b)

[2 2]


In [50]:
a = np.array([1, 2])

print(a * 3)

[3 6]


In [51]:
a = np.array([5, 6])
b = np.array([3, 4])

print(a @ b)

39


In [52]:
a = np.array([
    [1, 2],
    [4, 5]
])

b = np.array([
    [9, 8],
    [6, 5]
])

# 9 18
# 24 25



In [53]:
print(a + b)

[[10 10]
 [10 10]]


In [54]:
print(a - b)

[[-8 -6]
 [-2  0]]


In [55]:
print(a * b)

[[ 9 16]
 [24 25]]


In [56]:
print(a @ b)

[[21 18]
 [66 57]]


In [60]:
print(a)
print(a.T)

[[1 2]
 [4 5]]
[[1 4]
 [2 5]]


array([[ 1,  4],
       [16, 25]])